### ISSUE TITLE
initial tweet grabbing

### ISSUE THREAD

**Issue by libwtf** [jnicol/tweet-php#10]
is it possible, to run an inital grabbing, where it tries to get everything back to the first tweet?
to avoid ratelimiting, it would be nice to do it "step by step"...

**Comment by jnicol** [comment]
You can increase the number of tweets that are retrieved and displayed using the tweets_to_retrieve and tweets_to_display options, but the maximum number of tweets that the Twitter API will retrieve in one request is 200.

TweetPHP is designed to show a few of a user's latest tweets, so I don't have any plans to add an archiving feature like the one you have described.
