### ISSUE TITLE
No dates showing

### ISSUE THREAD

**Issue by leecollings** [jnicol/tweet-php#12]
The template <span class="date"></span> is appearing, but no dates are showing up in the values, regardless of different options given.

No obvious reason as to why. The dates are being returned in 'created_date' when using the array.

Any ideas?

**Comment by jnicol** [comment]
Have you modified the tweet_template option or any of the date options from their default values? The date should be displayed where {date} appears in tweet_template.

If you show me your TweetPHP config I can take a look.

**Comment by AndreasHill** [comment]
I had the same problem running on Windows (local test server).
My problem was solved with altering %e to %#d in the date_format option.

http://php.net/strftime

"The %e modifier is not supported in the Windows implementation of this function. To achieve this value, the %#d modifier can be used instead. The example below illustrates how to write a cross platform compatible function."

Hope it helps.

**Comment by leecollings** [comment]
Didn't realise that I posted this, but anyway, I still don't ever get any dates being returned by the plugin. What's more, I've changed the `tweet_template` option, and cleared the cache, but still the display is the default.

**Comment by jnicol** [comment]
I don't know if @AndreasHill's suggestion about Windows relates to this issue, but it is a good catch anyway. https://github.com/jnicol/tweet-php/commit/fa3bbafb3ff07dfc4271854d41badf3b4e376595 implements a fix for Windows servers.

**Comment by jnicol** [comment]
There's been no response on this one for a while so I'm closing it. Please reopen if the Windows server fix suggested above does now fix the original issue.
