### ISSUE TITLE
how do you actually add this to a php file and run it?

### ISSUE THREAD

**Issue by v3nt** [jnicol/tweet-php#24]
Can't seem to get this working and just want to grab a basic feed. Seems like all the paths aren't quite right? 

If i wanted to run `echo $TweetPHP->get_tweet_list();` how would i reference the TweetPHP class?

**Comment by jnicol** [comment]
```
<?php
require_once('path/to/TweetPHP.php');
$TweetPHP = new TweetPHP(array(
  // your options go here
));
echo $TweetPHP->get_tweet_list();
?>
```
