### ISSUE TITLE
tweets_to_retrieve and tweets_to_display don't match results?  

### ISSUE THREAD

**Issue by v3nt** [jnicol/tweet-php#25]
![fullsizeoutput_1e35](https://user-images.githubusercontent.com/6348562/34986243-beeb2d5e-faae-11e7-858b-9380e7d8070d.jpeg)
Ie I have these set as below but only 5 showing? Maybe replies and retweets are being included even though set to be excluded?

````
          'tweets_to_retrieve'    => 24, 
          'tweets_to_display'     => 12, // Number of tweets to display
          'ignore_replies'        => true, // Ignore @replies
          'ignore_retweets'       => true, // Ignore retweets
````

[screenshot attached]

**Comment by jnicol** [comment]
When you opt to ignore retweets and replies the Twitter API filters them out after retrieving the requested number of results, and unfortunately the number of tweets it returns may therefore not match the requested number.

In your case I am guessing that 19 of the 24 most recent tweets are retweets or replies, meaning that only 5 results are returned.

The workaround is to set a sufficiently high value for tweets_to_retrieve that even after the replies and retweets have been filtered out, you can be confident of having enough results left to satisfy the tweets_to_display value.
