### ISSUE TITLE
a way to set hashtags via options or another way? 

### ISSUE THREAD

**Issue by v3nt** [jnicol/tweet-php#26]
Via the JS version you can use

`<a class="twitter-timeline" href="https://twitter.com/hashtag/GE2015" data-widget-id="611481458889355264">#GE2015 Tweets</a>`

to filter the feed.

**Comment by v3nt** [comment]
heya - sorry to hassle but don't want to get too far down the line with this and realise there's no way to set hashes#s

**Comment by jnicol** [comment]
TweetPHP is designed only to query a single user's timeline using the `GET statuses/user_timeline` API endpoint. Retrieving hashtags requires communicating with the `GET search/tweets` endpoint.

I won't rule out the possibility of TweetPHP to allow searching too, but currently it isn't possible, I'm afraid.

**Comment by v3nt** [comment]
thanks @jnicol. When you add or remove the twitter_screen_name from the settings this seems to filter the content in some way. Is this a side effect of something else? (shall i open another ticket for this?) D.

**Comment by jnicol** [comment]
`twitter_screen_name` sets the twitter user whose timeline will be retrieved. Is it not working how you would expect?

**Comment by jnicol** [comment]
I have revamped TweetPHP to expose the Twitter Api endpoint and parameters as user defined options, in commit 487076990344c8a85bf35deaca539bca13db41a8. The readme includes and example of how to search for a hashtag, and all of the available parameters are listed in Twitter's documentation at https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets
