### ISSUE TITLE
Notice: Undefined variable: responsedata in tweet-php/TweetPHP.php on line 155

### ISSUE THREAD

**Issue by spadilha** [jnicol/tweet-php#27]
I think you have to change the variable $responsedata to $response on line 155.

From
$data = array_key_exists('statuses', $response) ? $response['statuses'] : $responsedata;

to
$data = array_key_exists('statuses', $response) ? $response['statuses'] : $response;

**Comment by jnicol** [comment]
Thank you! Fixed.
