### ISSUE TITLE
Readme error

### ISSUE THREAD

**Issue by bensinclair** [jnicol/tweet-php#5]
I noticed you had the following code example for the ['Autolink' section](https://github.com/jnicol/tweet-php#autolink).

    $autolinked_tweet = autolink($tweet);

I think you mean

    $autolinked_tweet = $TweetPHP->autolink($tweet);

No biggy. It just confused me and my simple brain for a few seconds there. Awesome script BTW!

**Comment by jnicol** [comment]
Thanks for spotting!
