### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by Advil-Robin** [jnicol/tweet-php#6]
Hi,

I configured all fields perfectley, but, how can I access the right stuff?

If I try to echo $TweetPHP->get_tweet_list();
In the TweetPHP.php file, the page keeps loading and it displays this:

Notice: Undefined variable: TweetPHP in C:\xampp\htdocs\tweet-php-master\TweetPHP.php on line 253

Fatal error: Call to a member function get_tweet_list() on null in C:\xampp\htdocs\tweet-php-master\TweetPHP.php on line 253

How to solve this problem?

**Comment by jnicol** [comment]
You shouldn't be making edits to TweetPHP.php.

You need to include TweetPHP.php in another php file (the one in which you wish the tweets to display), e.g.

require_once 'path/to/TweetPHP.php';

Then you can interact with the class as shown in the usage section of the README.
