### ISSUE TITLE
Most options don't work.

### ISSUE THREAD

**Issue by leecollings** [jnicol/tweet-php#8]
I know the options are being read because the debug one is the only one that has had any affect so far.

I've tried to limit the display of tweets to 1, and it's still showing two. Have also tried to remove the h2 header, but it still remains.

All done in this format:

    'twitter_wrap_open'         => '<ul id="tweets">',
    'twitter_wrap_close'        => '</ul>'

Any idea as to why the options are being ignored?

**Comment by leecollings** [comment]
By the way, even more worrying, even changing the default options in the TweetPHP.php file, doesn't have any effect on the output either.

What's going on here?

**Comment by leecollings** [comment]
Also, I can't see how dates of each tweets are supposed to appear? there's options for the display in twitter style, but not a generic 'On/Off' for the dates to appear next to the tweets.

By default, it seems as though no dates are shown at all, but I wan't them to be displayed. How can I turn on date display?

**Comment by jnicol** [comment]
TweetPHP caches its output so as not to exceed the Twitter API's rate limit. It sounds like you need to clear the contents of the cache directory. It's on my todo list to add an option to disable caching for dev purposes.

**Comment by leecollings** [comment]
Thanks, that's done the trick.

My second question regarding the date... Is the date generated by default
or does it need to be 'activated'?

On Thursday, 12 March 2015, Jonathan Nicol <notifications@github.com> wrote:

> TweetPHP caches its output so as not to exceed the Twitter API's rate
> limit. It sounds like you need to clear the contents of the cache
> directory. It's on my todo list to add an option to disable caching for dev
> purposes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jnicol/tweet-php/issues/8#issuecomment-78586223>.
>


-- 
Regards,

*Lee*

**Comment by jnicol** [comment]
By default the date is displayed as a link which follows the tweet. There is no need to activate it.

**Comment by leecollings** [comment]
Can you show me an example? As I haven't seen it appear anywhere. I assume
it's meant to appear in the Meta tag element?

On Friday, 13 March 2015, Jonathan Nicol <notifications@github.com> wrote:

> By default the date is displayed as a link which follows the tweet. There
> is no need to activate it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jnicol/tweet-php/issues/8#issuecomment-79341684>.
>


-- 
Regards,

*Lee*

**Comment by jnicol** [comment]
The default HTML output looks like this:

`<li><span class="status">{tweet}</span> <span class="meta"><a href="{link}">{date}</a></span></li>`

Note - I've made a few updates to the library today. Two that might affect you are:

- Replaced the old template options like `twitter_wrap_open` with a more flexible template system. See `twitter_template` and `tweet_template` options.

- Added `enable_cache` option which can be set to `false` to disable caching.

**Comment by leecollings** [comment]
Hmm There's no date displayed in the span meta tags. My output is as follows:

    <ul id="tweets">
        <li><span class="status">Setting up soon! <a href="http://twitter.com/search?q=%23excited">#excited</a></span><span class="meta"> <a href="http://twitter.com/Bellavou/status/532108609807998977"></a></span></li>
        <li><span class="status">Hello Twitter! <a href="http://twitter.com/search?q=%23myfirstTweet">#myfirstTweet</a></span><span class="meta"> <a href="http://twitter.com/Bellavou/status/531859634341310464"></a></span></li>
    </ul>

I'm using get_tweet_list, but I'm not using the meta_wrap options in my arguments, as I'm fine for them to be left as the default (as outlined in TweetPHP.php). This is correct, right?

**Comment by jnicol** [comment]
I've tested and the dates render for me:

    <li><span class="status">Setting up soon! <a href="http://twitter.com/search?q=%23excited">#excited</a></span> <span class="meta"><a href="http://twitter.com/Bellavou/status/532108609807998977">10:52 AM Nov 11th</a></span></li>

Off the top of my head I can't think why the dates wouldn't display for you, but I it sounds like one of the date parsing functions is failing silently. Some things you can try are:

- Set the `debug` option to true and see if any PHP errors are shown
- Set the `twitter_style_dates` option to `false` (or vice versa) and see if it makes a difference

Let me know if you come up with anything.

**Comment by leecollings** [comment]
Hm there is something I can update you with, I was working on a local copy of the site, and the dates weren't appearing.

So I uploaded the site to a subdomain, and the dates seem to be displaying.. although when using the twitter_style_dates option to true, it's still showing the full datetime stamp for the tweet, but I would assume that's because it's gone past a pre-determined period of time for that to take affect.

But the dates now seem to display, when the site is running on a live server, which might need some looking at maybe?

**Comment by jnicol** [comment]
Sounds like it's something to do with your local server's config. My testing was on a local server too (a XAMPP Mac stack). I'm going to close this issue, but if you do manage to pin it down please re-open the issue and let me know why it was breaking, to help me detect an incompatible configuration and output a relevant debug message.
